# Generated by Django 5.2.1 on 2025-05-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('NES', 'NES'), ('Sega Genesis', 'Sega Genesis'), ('Arcade', 'Arcade'), ('PlayStation 2', 'PlayStation 2')], default='NES', max_length=20),
        ),
    ]
