# Generated by Django 5.2.1 on 2025-05-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('ultra_rare', 'Ultra Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('mythic_rare', 'Mythic Rare')], default='common', max_length=20),
        ),
    ]
