# Generated by Django 5.2.1 on 2025-05-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_rarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='game',
        ),
    ]
